version: '3.9'

services:
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: playwright-runner
    environment:
      - BASE_URL=${BASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./tests:/tests
    working_dir: /tests
    command: >
      bash -c "
        echo 'Iniciando testes Playwright...' &&
        npm ci &&
        npx playwright install --with-deps &&
        npx playwright test --reporter=html
      "
