version: '3.9'

services:
  tests:
    image: mcr.microsoft.com/playwright:v1.48.0-jammy
    container_name: playwright-runner
    environment:
      - BASE_URL=https://automationintesting.online
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./tests:/tests
    working_dir: /tests
    command: >
      bash -c "
        echo 'Iniciando testes Playwright...' &&
        npm ci &&
        npx playwright install --with-deps &&
        npx playwright test --reporter=html
      "
