name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
jobs:
  docker:
    name: Test Execution Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t playwright-tests -f Dockerfile .
      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/app -v ${{ github.workspace }}/playwright-report:/app/playwright-report -w /app playwright-tests sh -c "npm install && npx playwright test"
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Add Playwright Report Link to Summary
        if: always()
        run: |
          echo "Playwright Test Report" >> $GITHUB_STEP_SUMMARY
          echo "[View HTML Report (via GitHub Pages)](https://pija-evandro.github.io/voidr-desafio-tecnico/)" >> $GITHUB_STEP_SUMMARY
  deploy:
    name: Deploy Playwright Report
    if: always()
    runs-on: ubuntu-latest
    needs: docker  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
  