name: CI/CD - Playwright-Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker pull mcr.microsoft.com/playwright:v1.56.1-noble

      - name: Run tests in Docker
        run: docker run --rm --ipc=host mcr.microsoft.com/playwright:v1.56.1-noble /bin/bash
        env:
         ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
         ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
         BASE_URL: ${{ secrets.BASE_URL }}
